### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'exec_' when closing Anki

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [glutanimate/speed-focus-mode#28] opened 2020-05-18 12:20 UTC
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
This error appears every time I try to quit anki. It's been happenning as soon as I updated from 2.1.23 to 2.1.26. I have to force quit to exit.

Disabling speed focus solves the issue.

Related to #27 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

Version 2.1.26 (70784154)
Python 3.8.1 Qt 5.14.1 PyQt 5.14.1

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-05-17 17:21:49
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Speed Focus Mode ['speed_focus_mode', 2019-06-29T00:35, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

#### Error message (if any)

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-17 17:21:49

Caught exception:
Traceback (most recent call last):
  File "aqt/main.py", line 973, in closeEvent
  File "aqt/main.py", line 436, in unloadProfileAndExit
  File "aqt/main.py", line 411, in unloadProfile
  File "aqt/main.py", line 519, in unloadCollection
  File "aqt/main.py", line 783, in closeAllWindows
  File "aqt/__init__.py", line 108, in closeAll
  File "aqt/main.py", line 515, in callback
  File "aqt/mediasync.py", line 143, in show_diag_until_finished
AttributeError: 'NoneType' object has no attribute 'exec_'


```

**Comment by Gueazy** [comment] 2020-06-05 13:33
Exactly the same problem, and i run anki on Mac
Thanks!

**Comment by glutanimate** [comment] 2020-06-05 18:05
Hi there,

Thanks for the report! Unfortunately I haven't been able to reproduce the issue on my end, so if you could help me with these additional questions, I'd really appreciate it:

1. Just to confirm: You've disabled all add-ons other than SFM and the issue still occurs? And disabling SFM after that makes the issue disappear? (i.e. if you run Anki with all add-ons disabled you don't see the issue)
2. Which version of SFM are you using? The one from AnkiWeb, or the beta version on here?
3. What do your SFM settings look like? Could you attach a screenshot of the corresponding deck options pane in one the affected decks?
5. Have you performed any other modifications, e.g. replaced the sound file with a custom one or anything like that? 
6. Do your cards have any sound files on them? Have you noticed that the issue occurs when you've reviewed cards that have sounds / media files on them?
7. And specifically @thiswillbeyourgithub: What operating system are you on?

Thanks a lot in advance!

**Comment by glutanimate** [comment] 2020-06-05 18:21
Just to make 2.) easier (since there is no version number visible in the UI): If your add-on has this line in the deck options, it's the current beta:

![Screenshot_20200605_201416](https://user-images.githubusercontent.com/5459332/83909466-21e0b280-a769-11ea-9fee-6ebad2c2081f.png)

Judging by the info in #27, I would be really surprised if the AnkiWeb release was affected.

Also, one more question as it would really help narrow things down:

- Do you guys have the option to *Automatically sync on profile open/close* enabled in Anki's preferences? (as pointed to by @giovannihenriksen [here](https://github.com/glutanimate/speed-focus-mode/issues/27#issuecomment-633514218))

**Comment by Gueazy** [comment] 2020-06-05 18:23
1. Yes I have disabled all add-ons one per one, and disabling SFM only make the issue disappear
2. The SFM version from AnkiWeb. I tried removing and reinstalling to see if it changes anything, but no changes
3. I can't bc SFM is disabled but I had basic settings, I just changed the time and disabled the "again after x seconds"
4. No modification
5. I don't have audio on my cards (i'm using anki for medicine) but the issue occurs only when i'm trying to **quit** anki

Sorry for my bad english!!! Thanks for you quick response and all your work

**Comment by Gueazy** [comment] 2020-06-05 18:25
My bad! I was using the beta, with the AnkiWeb version everything works!

**Comment by Gueazy** [comment] 2020-06-05 18:27
And finally, yes I have the _Automatically sync on profile open/close_ enabled

**Comment by on115** [comment] 2020-08-27 19:35
I am also using the beta version (for the pause feature) and am having the same problem when trying to close anki.

**Comment by giovannihenriksen** [comment] 2020-09-13 11:36
This seems to be no longer occurring in the latest version of Anki (2.1.33).

**Comment by Mansonum** [comment] 2021-01-16 15:00
same issue here. And the latest version of Anki 2.1.35 recreate this bug as well

**Comment by glutanimate** [comment] 2021-08-28 17:13
Thanks a bunch for the reports, guys! This should now be fixed in the `main` branch and find its way into the next release (which will go live on [09/09 on Patreon](https://www.patreon.com/posts/long-overdue-55374245) and be posted to AnkiWeb later this fall.

**Closed by glutanimate** 2021-08-28 17:13 UTC
Labels: bug, more info needed
