### ISSUE TITLE
Audio Not Playing

### ISSUE THREAD

**Issue by BDubbB** [glutanimate/speed-focus-mode#25] opened 2020-03-12 21:35 UTC
Hi,

I'm using Anki 2.1 on Windows 10 64-bit with this add-on. I get a message in the bottom left when it is supposed to play the audio file, but the audio file doesn't play. I haven't messed with anything, and I found the folder with the audio file, just to make sure it's there, and it is. alert.mp3 is in AppData\Roaming\Anki2\addons21\Speedfocus.

Any help would be greatly appreciated!

**Comment by Cupbox** [comment] 2020-03-13 12:59
Same issue here. Audio initially works and at some point stops working. I notice the problem occurs more often with cards with Audio.
It's not just the addon sound that's affected. All of Anki's audio playing ability stops until a reboot.
Problem started around Anki 2.1.20.

**Comment by glutanimate** [comment] 2020-03-13 14:33
Hi and thanks for the reports, guys.

Anki 2.1.20+ seems to be suffering from some general issues with audio playback, so it would be important to isolate whether this is an add-on specific issue or not. Since the add-on is not doing anything undocumented, just using Anki's default way to play media (in the same manner as audio on a card would be played), chances are this is a manifestation of an Anki bug.

For a number of related reports on Anki's forums please see here: 

https://anki.tenderapp.com/discussions/ankidesktop/39628-audio-not-playing

https://anki.tenderapp.com/discussions/ankidesktop/39307-2120-cards-stop-reproducing-sound-after-some-reviews

**Comment by Cupbox** [comment] 2020-03-14 04:12
Thanks for the info Glutanimate. 
I'll monitor those threads.

**Comment by glutanimate** [comment] 2020-03-15 19:50
@Cupbox Glad to hear the beta works!

Closing this as the issue is fixed upstream.

**Closed by glutanimate** 2020-03-15 19:50 UTC
Labels: more info needed, upstream
